---
title: "oip postprocess"
author: "Paul Leiby"
date: "5/1/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(readxl)
```

## Data Section'

```{r}
# Warning: following is machine-dependent path
#. Could use here("..")
# machine_base_path = "/Users/paulleiby/Documents" # PL Mac
machine_base_path = "D:Workfiles" # PL Amanda Home Desktop
OIP_model_output_path = "/Papers/2006OilImportPremium/Analysis"
# OIP_model_output_path = here("..") does this work
# Expected location of output files for each run of OIP (xlsx format)
inputdata_subpath = "Data/inputdata" # path relative to project folder
output_subpath <- "Output" # destination for any output
```

### Specify set of OIP Runs to be Processed

```{r}
model_versionyear <- "OIP2022"
model_subversion <- "v31" # note that tradition is lower-case v here
```

```{r}
str_cmp_num <- function(s1, s2) {
  # returns position of first character difference
  # (mapply is faster than loop, but only works for equal-length objects)
  mapply(function(x, y) which(x != y)[1], 
     strsplit(s1, ""), strsplit(s2, ""))
}

str_cmp_num("Hello", "Helmo")
```

```{r}
runset <- paste0("r0", 1:4)

runset

AEOyear = "A2022"
run_years = paste0("YR", c(2023, 2024, 2025, 2026, 2030, 2035, 2040, 2045, 2050 ))
default_switchstring = "DE1CO1PC1"

runset_num = 3
case_file_names = paste0(model_versionyear, model_subversion,
                         runset[runset_num], "_", AEOyear, run_years, 
                         default_switchstring)
```

```{r}
# add caseset case-number extension (N1..Nn) to filename
#. Unfortunately, this number is particular to the order in
#. which the cases are run, rather than their content
for (n in 1:length(case_file_names)) {
  case_file_names[n] <- paste0(case_file_names[n], "SN", n)
}
```

```{r}
case_file_names
```

```{r}
# test that an expected case is in the set
case_example = "OIP2022v31r03_A2022YR2023DE1CO1PC1SN1"

case_example %in% case_file_names
```

```{r}
# # note that tradition is upper-case v here for version number in directory names
input_subdirs <- c(paste0(toupper(model_subversion), runset))
input_subdirs

input_path_components <- c(inputdata_subpath, toupper(model_subversion), input_subdirs[runset_num])
input_path_components
```

```{r findingFilesAndDirs}
list_of_dirs <- list.dirs(here(inputdata_subpath), recursive=FALSE) # list of subdirectories to "input"
list_of_dirs

list_of_files <- list.files(here(paste(input_path_components, collapse = "/")), recursive=FALSE) # list of files in one runset directory
list_of_files
```


```{r test_foundFilesAndDirs}
"OIP2022v31r03_A2022YR2023DE1CO1PC1SN1.xlsx" %in% list_of_files

```


```{r}
case_num <- 1


rslt <- here(
  paste(input_path_components, collapse = "/"),
  paste0(case_file_names[case_num],
         # "SN", case_num,
         ".xlsx")
  ) %>%
  read_excel()

class(rslt)

```

```{r defFn_construct_case_file_name}
construct_case_file_name <- function(nset, ncase) {
  # nset: number of set of cases (usually years for same param values)
  # ncase: number of case within set of cases"
  # Globals: that define cases:
  #   model_versionyear, model_subversion, runset, AEOyear, run_years, default_switchstring
  c_file_name = paste0(
    model_versionyear, 
    model_subversion, 
    runset[nset], "_", 
    AEOyear, 
    run_years[ncase], 
    default_switchstring,
    "SN", ncase
    )
  c_file_name
}

```

```{r defFn_read_one_excel_case}
read_one_excel_case <- function(case_file_name, path_spec) {
  
  full_case_path_spec <- here(
      paste(path_spec, collapse = "/"),
      paste0(case_file_name, ".xlsx")
    )
  
  # check for file existence first
  if (file.exists(full_case_path_spec)) {
    rslt <- read_excel(full_case_path_spec, range = "B11:AA39") %>%
      rename(Year = `Year/Index`) %>% # clean up
      select(Year, Variable, starts_with("pi_")) %>% # keep pi components (drops derivatives, case selector indices)
      filter(!is.na(Year) & Year != 0) # drop some stats not needed or complete (drops Std. Dev, Variance)
  } else {
    rslt <- NULL
  }
}
```



```{r defFn_extract_basic_rslts}
extract_basic_rslts <- function(raw_rstl) {
  rsltx <- rslt[10:38,2:27]
  names(rsltx) <- rsltx[1,]
  rsltx <- rsltx[2:nrow(rsltx),]
  rsltx <- rsltx %>%
    rename(Year = `Year/Index`) %>%
    select(Year, Variable, starts_with("pi_")) %>%
    filter(!is.na(Year) & Year != 0)
}

```

```{r}
runset_num = 3
case_num = 1

case_file_name = construct_case_file_name(runset_num, case_num)
rslt <- read_one_excel_case(case_file_name, input_path_components)
```


```{r}
process_one_set_of_cases <- function() {
  
  print(paste0("Processing `model_versionyear` ", model_versionyear, 
      ", `sub_version` ", model_subversion))
  rslts = tibble() # initialize results df
  
  for (case_num in 1:9) { # assume 9 cases (years) per set. 
    
    print(paste0("  reading case_set ", runset_num, " case ", case_num))
    case_file_name = construct_case_file_name(runset_num, case_num)
    rslt <- read_one_excel_case(case_file_name, input_path_components)
    
    if (is.null(rslt)) {
      print(paste0("    Error or file not found for case ", case_file_name))
    } else { # non-NULL return from file read
      #  extract_basic_rslts() -> rslt
      if (nrow(rslts) == 0) { # first non-NULL result, initialize df format
        rslts <- rslt
      } else { # concatenate rows (expecting consistent columns)
        rslts <- bind_rows(rslts, rslt)
      }
    }
  }
  
  rslts <- rslts %>%
    mutate(
      model_versionyear = model_versionyear,
      model_subversion = model_subversion,
      runset_num = runset_num,
      case_num = case_num,
      case_file_name = case_file_name
    )
    rslts
}
```


```{r}
set_rslts <- process_one_set_of_cases()
```

```{r saveRsltsToCSV}
save_results <- T
if (save_results) {
  write_csv(set_rslts, here(output_subpath, paste0(model_versionyear, model_subversion, runset[runset_num], ".csv")))
}

dim(set_rslts)

```

